<a href="https://colab.research.google.com/github/jaimeisaac2020/Python-analsisis-basicos/blob/mi-github/4_Merging_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Importando libreriasa relevantes

In [1]:
import numpy as np
import pandas as pd

#### cargando dataset

In [2]:
marketing_sample1 = pd.read_csv("marketing_campaign_merge1.csv")
marketing_sample2 = pd.read_csv("marketing_campaign_merge2.csv")

#### Inspeccionando los datasets

In [ ]:
marketing_sample1.shape

(2240, 3)

In [3]:
marketing_sample1.head()

     ID  Year_Birth   Education
0  5524        1957  Graduation
1  2174        1954  Graduation
2  4141        1965  Graduation
3  6182        1984  Graduation
4  5324        1981         PhD

In [ ]:
marketing_sample1.shape

(2240, 3)

In [4]:
marketing_sample2.head()

     ID Marital_Status   Income
0  5524         Single  58138.0
1  2174         Single  46344.0
2  4141       Together  71613.0
3  6182       Together  26646.0
4  5324        Married  58293.0

In [ ]:
marketing_sample2.shape

(2240, 3)

#### Fusionar los dos conjuntos de datos en uno nuevo basado en la columna común (es decir, ID).

In [ ]:
merged_data = pd.merge(marketing_sample1,marketing_sample2,on = "ID")

In [ ]:
merged_data.shape

(2240, 5)

In [ ]:
merged_data.head()

     ID  Year_Birth   Education Marital_Status   Income
0  5524        1957  Graduation         Single  58138.0
1  2174        1954  Graduation         Single  46344.0
2  4141        1965  Graduation       Together  71613.0
3  6182        1984  Graduation       Together  26646.0
4  5324        1981         PhD        Married  58293.0